### ISSUE TITLE
Can't get this to work with vim-polyglot, or at all

### ISSUE THREAD

**Issue by statico** [alampros/vim-styled-jsx#1]
I'm using [vim-polyglot](https://github.com/sheerun/vim-polyglot), which includes [vim-jsx](https://github.com/mxw/vim-jsx) and [pangloss/vim-javascript](pangloss/vim-javascript), and I don't get any syntax highlighting in my inline styles in my CSS. I've also tried removing `vim-polyglot` and installing vim-jsx and vim-javascript manually. My .vimrc is hosted [here](https://github.com/statico/dotfiles/blob/master/.vim/vimrc), but I've tried starting Vim without a config using `vim -u NONE foo.js`. Any ideas?

![image](https://user-images.githubusercontent.com/137158/30517757-0bf741aa-9b1e-11e7-8942-a379b47486a9.png)

#### Code in question

https://github.com/statico/aspen/blob/cb65123f1530b410ee3d941fd08399601678edba/pages/index.js#L182-L194

#### vim --version

```VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May  2 2017 03:55:34)
MacOS X (unix) version
Included patches: 1-596
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     -gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
-clientserver    +insert_expand   +packages        -toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            +ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      -mouseshape      +startuptime     -xsmp
+eval            +mouse_dec       +statusline      -xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary      
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework Cocoa   -mmacosx-version-min=10.12 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.24.1/lib/perl5/5.24.1/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc -F/usr/local/opt/python/Frameworks -framework Python   -lruby.2.4.1 -lobjc    
```

**Comment by statico** [comment]
FWIW, in that sample I'm using the `<style>` tag without the `jsx` attribute. Using the tag like `<style jsx>` doesn't make a difference.

**Comment by fleischie** [comment]
Hey @statico. :wave:

`vim-styled-jsx` is neither installed via [vim-polyglot](https://github.com/sheerun/vim-polyglot) nor your `.vimrc`. Are you sure this package is installed in your setup?

Edited: Apart from that, this plugin only detects styled-jsx if you explicitly write `<style jsx>` or `<style jsx global>` or `<style global jsx>`. It at least needs `style` and `jsx` in an XML Tag. (The actual regexp is `"<style.*jsx.*>"`.

**Comment by statico** [comment]
Hey! 😄 

So it's a load order issue. Normally my runtime path looks something like this:

`runtimepath=~/.vim,~/.vim/bundle/molokai,~/.vim/bundle/vim-pathogen,~/.vim/bundle/vim-polyglot,~/.vim/bundle/vim-styled-jsx,/usr/local/share/vim/vimfiles,
/usr/local/share/vim/vim80,/usr/local/share/vim/vimfiles/after,~/.vim/bundle/vim-styled-jsx/after,~/.vim/bundle/vim-polyglot/after,~/.vim/after,/usr/local/o
pt/fzf,~/.fzf`

And the colors don't show up. But if I `mv ~/.vim/bundle/vim-styled-jsx ~/.vim/bundle/aaaaaaaaa` so that vim-styled-jsx in the runtimepath _before_ vim-polyglot, everything is fine.

![image](https://user-images.githubusercontent.com/137158/30784785-dd519b36-a110-11e7-96f1-c7ef10961db0.png)

Thanks for the suggestions. cc @sheerun (vim-polyglot) who might be interested.

**Comment by sheerun** [comment]
You can also disable single syntax as described in the readme :) Then the load order doesn't matter probably
