### ISSUE TITLE
Odd colouring of selectors

### ISSUE THREAD

**Issue by mminer** [alampros/vim-styled-jsx#3]
![odd-colours-demo](https://user-images.githubusercontent.com/267284/55645448-77988400-578d-11e9-87d0-dd6a9b4221eb.gif)

Some notable plugins I'm using that might be causing conflicts include vim-polyglot and the Molokai colour scheme.

**Comment by theycallmeswift** [comment]
+1. Seeing this with the OceanicNext color scheme too.

![image](https://user-images.githubusercontent.com/434373/89734987-4721c380-da2d-11ea-8dc6-048c9573fde7.png)

**Comment by alampros** [comment]
Apologies, but I do not have the time/desire to maintain this repo anymore and will be archiving this repo.
